# Generated by Django 5.1.2 on 2024-12-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='autor',
            new_name='author',
        ),
    ]
